.NOTPARALLEL: $(RUMPRUN_PKGS_DIR)/lib/watchdog.o $(RUMPRUN_PKGS_DIR)/lib/libssl.a
$(RUMPRUN_PKGS_DIR)/lib/watchdog.o:
	$(MAKE) -C ../watchdog

$(RUMPRUN_PKGS_DIR)/lib/libssl.a:
	$(MAKE) -C ../$(RUMPRUN_SSL)

.PHONY: watchdog libssl
watchdog: $(RUMPRUN_PKGS_DIR)/lib/watchdog.o
libssl: $(RUMPRUN_PKGS_DIR)/lib/libssl.a
